kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    repo: mountaindude/butler
    dockerfile: src/Dockerfile
    auto_tag: true
    tags: 
      - latest
      - '3.0.3'
