kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    repo: ptarmiganlabs/butler
    dockerfile: src/Dockerfile
    context: src
    # auto_tag: true
    tags:
    - latest
    - 'v3.0.4'
    - '3.0.4'
  when:
    event:
    - tag

# trigger:
#   event:
#   - tag